export const Users = [
	{
		id: 1,
		fullName: 'Артем Дудко',
		exp: '2000',
		level: '10',
		achievements: [
			'Золотой знак',
			'Быстрое обучение',
			'Помощник сообщества',
			'admin',
			'Кофе-зависимый  ',
		],
		about: 'Frontend разработчик с 2-летним опытом. Люблю React. Ученик 6Л',
		avatar: '👨‍💻',
		skills: ['JavaScript', 'React'],
		progress: 100,
	},

	{
		id: 2,
		fullName: 'Алтынбаева Эльмира',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 3,
		fullName: 'Ботян Вероника',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 4,
		fullName: 'Гомза Ксения',
		exp: '0',
		level: '0',
		achievements: ['Счастливчик'],
		about: 'Ученица 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 5,
		fullName: 'Зозуля Вера',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 6,
		fullName: 'Колтович Вячеслав',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 7,
		fullName: 'Кушаева Анастасия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 8,
		fullName: 'Лукашеня Михаил',
		exp: '0',
		level: '0',
		achievements: ['Дизайнер'],
		about: 'Занимаюсь Дизайном 5 лет Ученик 6Л',
		avatar: '👨‍💻',
		skills: ['Photoshop', 'Illustrator', 'Animate'],
		progress: 0,
	},
	{
		id: 9,
		fullName: 'Мишук Захар',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 10,
		fullName: 'Рудаков Тимур',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 11,
		fullName: 'Рычков Максим',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 12,
		fullName: 'Стриго Вера',
		exp: '0',
		level: '0',
		achievements: [''],
		about: 'Ученица 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 13,
		fullName: 'Судник Илья',
		exp: '0',
		level: '0',
		achievements: ['Тигр'],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 13,
		fullName: 'Федор Томашев',
		exp: '0',
		level: '0',
		achievements: ['Диванный стратег'],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 14,
		fullName: 'Чернухо Егор',
		exp: '0',
		level: '0',
		achievements: ['Молодец!'],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 15,
		fullName: 'Шибко Александр',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Л',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 16,
		fullName: 'Литвиненко Семен',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 17,
		fullName: 'Лихачевский Ярослав',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 18,
		fullName: 'Макаров Вадим',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 19,
		fullName: 'Малишевский Роман',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 20,
		fullName: 'Махлаев Артур',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 21,
		fullName: 'Медведев Евгений',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 22,
		fullName: 'Медведева Карина',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 23,
		fullName: 'Оскирко Арсений',
		exp: '10',
		level: '0',
		achievements: ['Счастливчик', 'Любознательный'],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 1,
	},
	{
		id: 24,
		fullName: 'Прокопенко Анастасия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 25,
		fullName: 'Рубанова Ксения',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 26,
		fullName: 'Сокирка Ксения',
		exp: '0',
		level: '0',
		achievements: ['Умница'],
		about: 'Ученица 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 27,
		fullName: 'Соловей Алиса',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 28,
		fullName: 'Хацкевич Никита',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 29,
		fullName: 'Шурыгина Яна',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Е',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 30,
		fullName: 'Будай Александра',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 31,
		fullName: 'Герасимчук Милана',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 32,
		fullName: 'Дикун София',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 33,
		fullName: 'Жлоба София',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 34,
		fullName: 'Иващенко Даниил',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 35,
		fullName: 'Кузьминова Анна',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 36,
		fullName: 'Макович Валерия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 37,
		fullName: 'Новикова Маргарита',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 38,
		fullName: 'Позняк Анастасия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 39,
		fullName: 'Пранович Кира',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 40,
		fullName: 'Симан Александра',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 41,
		fullName: 'Тихон Мария',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 42,
		fullName: 'Хранцкевич Никита',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 43,
		fullName: 'Царук Каролина',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6А',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 44,
		fullName: 'Бабарикин Эльдар',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 45,
		fullName: 'Бурденко Марьяна',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 46,
		fullName: 'Гончарова Диана',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 47,
		fullName: 'Жигарева Ирина',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 48,
		fullName: 'Молчанов Иван',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 49,
		fullName: 'Морская Валерия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 50,
		fullName: 'Татаринова Екатерина',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 51,
		fullName: 'Трошкина Валерия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 52,
		fullName: 'Хамицевич Андрей',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 53,
		fullName: 'Хомичук Александра',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 54,
		fullName: 'Чичикова Ульяна',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 55,
		fullName: 'Шавель Ксения',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 56,
		fullName: 'Янучек Фёдор',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 57,
		fullName: 'Янушкевич Эмилия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Б',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 58,
		fullName: 'Альховик Александра',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 59,
		fullName: 'Альховик Егор',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 60,
		fullName: 'Власенко Виктория',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 61,
		fullName: 'Гончар Полина',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 62,
		fullName: 'Гончаренко Александр',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 63,
		fullName: 'Дубровская Амалия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 64,
		fullName: 'Зайцева Виктория',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 65,
		fullName: 'Кунина Валерия',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученица 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 66,
		fullName: 'Магер Егор',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 67,
		fullName: 'Мухин Данила',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
	{
		id: 68,
		fullName: 'Новиченко Александр',
		exp: '0',
		level: '0',
		achievements: [],
		about: 'Ученик 6Д',
		avatar: '👨‍💻',
		skills: [],
		progress: 0,
	},
]

// Функция для обновления данных
export const updateUsersData = newUsers => {
	// В реальном приложении здесь может быть запрос к API или сохранение в localStorage
	console.log('Данные пользователей обновлены:', newUsers)
	return [...newUsers]
}
